### ISSUE TITLE
调整新闻子频道的位置后，新闻内容不更新

### ISSUE THREAD

**Issue by way1989** [jaydenxiao2016/AndroidFire#1]
比如说我将军事和历史频道调整位置，发现军事标题下还是历史的新闻。

**Comment by cuBblu** [comment]
调整新闻子频道的位置后，新闻内容不更新 #1

**Comment by cuBblu** [comment]
调整新闻子频道的位置后，新闻内容不更新 #1

**Comment by jaydenxiao2016** [comment]
该bug已修复，原因是FragmentManager对之前fragment有了缓存，清掉就可以了。感谢提bug
