### ISSUE TITLE
关于GSON部分解析

### ISSUE THREAD

**Issue by lindue** [jaydenxiao2016/AndroidFire#13]
@GET("nc/article/{type}/{id}/{startPage}-20.html")
    Observable<Map<String, List<NewsSummary>>> getNewsList(
            @Header("Cache-Control") String cacheControl,
            @Path("type") String type, @Path("id") String id,
            @Path("startPage") int startPage);
分析到这里后分析不下去了，看不懂这是什么原理，
我想去在这里解析JSON返回，请问如何做？

**Comment by xuchenchen** [comment]
你看完retrofit2的用法后这里自然会明白的

**Comment by lindue** [comment]
已经解决这个问题了
