### ISSUE TITLE
你的关注这个模块有问题，一进去APP就崩溃

### ISSUE THREAD

**Issue by quguangle** [jaydenxiao2016/AndroidFire#14]
我看了一下打印的问题，一开始是你CircleZoneActivity的XML文件中Editext的背景色文件id找不到，后来我册除后，又报了其他的错误。估计是这个模块那里写的有问题。希望楼主尽快解决，我很关注你这个APP。

**Comment by xuchenchen** [comment]
找到drawable/selector_gray_border这个布局中，将其中的 <solid android:color="?attr/dayNightBackground"/>改为别的就行例如改为 <solid android:color="@color/gray"/>，这样可以不报错

**Comment by jaydenxiao2016** [comment]
已修改，感谢
