### ISSUE TITLE
当我网速不好时，在刷新就出现了这样的界面。

### ISSUE THREAD

**Issue by quguangle** [jaydenxiao2016/AndroidFire#16]
![image](https://cloud.githubusercontent.com/assets/17522396/20513753/0dd5cac8-b0c3-11e6-8f5d-09402465d9d4.png)

**Comment by quguangle** [comment]
当网络错误时，显示的UI一直显示在界面上，这样带来的用户体验很不好，在加载的过程中一旦网络出现了错误，就会这样。我觉得没必要在显示这个网络错误的UI。

**Comment by quguangle** [comment]
只需要在第一次进去，如果网络错误就展示这个UI，进去之后显示数据，如果在加载数据，此时网络有错误（比如网速较慢）这时就没有必要在显示这个UI,只需要在底部给个提示就行了。个人意见。

**Comment by jaydenxiao2016** [comment]
感谢提宝贵意见，已改
