### ISSUE TITLE
BUG一个

### ISSUE THREAD

**Issue by xiong1234777** [jaydenxiao2016/AndroidFire#3]
在新闻详情页用WebView打开，跳转到NewsBrowserActivity
返回时崩溃，onDestroy调用时，webView为空
原因是先调用了super.onDestroy()，以致于解绑了ButterKnife
闲着没事说一声，哈哈

**Comment by WangChangQin** [comment]
我也发现这个bug了哈哈

**Comment by jaydenxiao2016** [comment]
此bug已修复，感谢提bug
