### ISSUE TITLE
Caused by: java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType

### ISSUE THREAD

**Issue by zhushuhao** [jaydenxiao2016/AndroidFire#6]
mPresenter = TUtil.getT(this, 0);
Tutil.getT中:
return ((Class<T>) ((ParameterizedType) (o.getClass()
                   .getGenericSuperclass())).getActualTypeArguments()[i])
                    .newInstance();
这一句报错：Caused by: java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
请问这个如何解决

**Comment by KevinHero** [comment]
这里应该是混淆代码造成的。 
我能正常编译，debug版本能正常使用，release包不行，报这个错误。
 ![](http://odf775exx.bkt.clouddn.com/126470681058693247.jpg)

**Comment by GuoZhaoHui628** [comment]
@aPandaGrandpa  需要将TUtil.class混淆吗。我反编译看了下，确实这个没被混淆，这里感到有点奇怪，为什么开启混淆后，这种普通的类为什么没被混淆呢。这个proguard-rules.pro文件中又没有写防止它被混淆的代码
大佬 如果还在关注这个问题，帮忙瞧一瞧 谢谢了
